# Generated by Django 6.0.5 on 2026-05-25 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('file_name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct'), (2, 'Scope 2 — Indirect (Energy)'), (3, 'Scope 3 — Indirect (Value Chain)')])),
                ('category', models.CharField(choices=[('stationary_combustion', 'Stationary Combustion'), ('mobile_combustion', 'Mobile Combustion'), ('purchased_electricity', 'Purchased Electricity'), ('business_travel_air', 'Business Travel — Air'), ('business_travel_hotel', 'Business Travel — Hotel'), ('business_travel_ground', 'Business Travel — Ground'), ('purchased_goods', 'Purchased Goods & Services')], max_length=50)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit', models.CharField(max_length=30)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('raw_quantity', models.CharField(blank=True, max_length=100)),
                ('raw_unit', models.CharField(blank=True, max_length=50)),
                ('raw_row_number', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('facility', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.datasource')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('locked', 'Locked')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.emissionrecord')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope'], name='ingestion_e_tenant__87a790_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='ingestion_e_tenant__2905d3_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['data_source'], name='ingestion_e_data_so_4e2c37_idx'),
        ),
    ]
